### ISSUE TITLE
Section 1 - meta

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_network_prediction#1]
- [ ] *BOX 1: Biological Examples* @DominiqueCaron #16 
  - [x] What is the paper about? @tpoisot #6 
  - [x] Who would benefit from it? **Laura**
  - [x] Why do we need to predict interactions between species? @Norma-Forero  // @graciellehigino #47 
  - [x] Why predict networks before interactions? @gottacatchenall 
  - [x] What is currently limiting our ability to predict network structure? @TanyaS08  // @FrancisBanville #17
  - [x] What is currently enabling our ability to predict network structure? @FrancisBanville #33 
  - [x] Conceptual figure @gottacatchenall 

**Main PR**: #54

**Comment by tpoisot** [comment]
:tada: one question tentatively merged into the integration branch!
