### ISSUE TITLE
reviewer one

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/ms_network_prediction#120]
- [ ] Validation: metrics #121 
- [x] Validation: uncertainty in training, subsampling, bootstraping #128
- [x] Proof-of-concept validation figure: #127 & #130
- [x] Inflating dataset with positive interactions clarification #122
- [ ] Preprints that we cite #123
- [ ] Using network properties as alternative to embedding to predict structure #124
- [x] More clear delineation of uni-,bi-,and k-partite networks #125
- [x] More details on flow in networks #126
- [x] proof of concept figure #132 #130 
- [x] refer to proof-of-concept traits data which is hard to find #131 
- [x] British spellings #141

**Comment by TanyaS08** [comment]
There is probably some 'fine-tuning' that can be done to the new figures but that can probably wait until we have the bulk of things are organised. Not sure if that warrants it's own issue though...
