### ISSUE TITLE
Section 2 - primer

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_network_prediction#2]
## A primer on predictive (network) ecology **[@gottacatchenall  + @tpoisot ]**
 - [x] What are the most important properties of networks to predict? **[@Norma-Forero  + @tpoisot ]** #8 
 - [x]  What is the added value of using machine learning? **[@FrancisBanville ]** #34 
 - [x] How do we fit a predictive model? **[@gabrieldansereau ]** #11 
 - [ ] How do we validate a predictive model? **[@gottacatchenall ]** #22
 - [ ] How do we propagate uncertainty through a predictive model? **[@gottacatchenall  + @FrancisBanville  + Laura]** #35 
 - [x] How do we determine what interaction networks are feasible? **[@TanyaS08  :paw_prints: + @gottacatchenall ]** #19
