### ISSUE TITLE
Section 3 - interactions

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_network_prediction#3]
- [ ] *Box 2: Machine Learning Illustration* **[@tpoisot]** #9
 - [x]  What is a species interaction? **[@TanyaS08  :paw_prints: + @BenMerSci ]** #21
 - [x]  How do we predict how species that have never co-occurred will interact? **[@DominiqueCaron  + @graciellehigino ]** #20 
 - [x]  What does interaction strength mean? **[@BenMerSci ]** #41
- [ ]  How are interaction strengths actually inferred? **[@BenMerSci  + SeNd HeLp]** #43
- [x]  Could we use hypergraphs and multi-layer networks to predict more interactions? **[@Norma-Forero  + @tpoisot ]** #30 

Main PR is #56
