### ISSUE TITLE
Section 4 - spatial component

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_network_prediction#4]
## Network predictions must have a spatial component **[@gottacatchenall, Laura ]**
 - [x] *Everything is connected figure* **[@TanyaS08]** #59
 - [x] How much do networks vary over space? **[@DominiqueCaron ]** #45 
 - [x] How do we predict what the species pool at a particular location is? **[@gabrieldansereau ]** #23 
 - [x]  How could predictions for individual species, such as those used by IPBES/IUCN, be improved by considering ecological interactions? **[@gabrieldansereau ]** #25 
  - [x]  What is the spatial scale suitable for the prediction of species interactions? **[@graciellehigino ]** #49 

**Main PR:** #58
